services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: sanidad
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  # Nombre del servicio MySQL (el contenedor "db")
      PMA_PORT: 3306
    ports:
      - "8080:80"  # Accederás a phpMyAdmin en http://localhost:8080
    depends_on:
      - db

volumes:
  dbdata: