<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        // Seed Users
        DB::table('users')->insert([
            [
                'first_name'     => 'Carlos',
                'last_name'      => 'Pérez Ruiz',
                'email'          => 'carlos.perez@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'student',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Marcos',
                'last_name'      => 'Gómez Blanco',
                'email'          => 'marcos.gomez@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'student',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Manuel',
                'last_name'      => 'Álvarez Medrano',
                'email'          => 'manuel.alvarez@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'student',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Raúl',
                'last_name'      => 'Fernández Díaz',
                'email'          => 'raul.fernandez@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'student',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Ariana',
                'last_name'      => 'García Manzano',
                'email'          => 'ariana.garcia@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'teacher',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Miriam',
                'last_name'      => 'López Rouco',
                'email'          => 'miriam.lopezrouco@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'teacher',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Marta',
                'last_name'      => 'Ramirez Castillo',
                'email'          => 'marta.ramirez@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'teacher',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Lucía',
                'last_name'      => 'Fernández Soto',
                'email'          => 'lucia.fernandez@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'admin',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            [
                'first_name'     => 'Juan',
                'last_name'      => 'Valdés Morilla',
                'email'          => 'juan.valdes@educamadrid.com',
                'hashed_password'=> Hash::make('clave'),
                'first_log'      => false,
                'user_type'      => 'admin',
                'created_at'     => Carbon::now('Europe/Madrid')
            ],
            
        ]);

        // Seed Materials
        DB::table('materials')->insert([
            ['material_id' => 1, 'name' => 'PEAN', 'description' => 'Pinza de sujeción', 'image_path' => 'materials/pean.jpg'],
            ['material_id' => 2, 'name' => 'Tijeras', 'description' => 'Tijeras quirúrgicas', 'image_path' => 'materials/tijeras.jpg'],
            ['material_id' => 3, 'name' => 'Tijeras Vendaje', 'description' => 'Tijeras para corte de vendajes', 'image_path' => 'materials/tijeras_vendaje.jpg'],
            ['material_id' => 4, 'name' => 'Pinzas de Disección c/ y s/ Dientes', 'description' => 'Pinzas de disección con y sin dientes', 'image_path' => null],
            ['material_id' => 5, 'name' => 'Estelites', 'description' => 'Material utilizado en cirugía dental', 'image_path' => 'materials/estelites.jpg'],
            ['material_id' => 6, 'name' => 'Kocher Rectas/Curvas', 'description' => 'Pinzas Kocher rectas y curvas', 'image_path' => 'materials/kocher_rectas_curvas.jpg'],
            ['material_id' => 7, 'name' => 'Kocher Plástico', 'description' => 'Pinzas Kocher de plástico', 'image_path' => 'materials/kocher_plastico.jpg'],
            ['material_id' => 8, 'name' => 'Sonda Acanalada', 'description' => 'Sonda con canalización', 'image_path' => 'materials/sonda_acanalada.jpg'],
            ['material_id' => 9, 'name' => 'Porta Agujas', 'description' => 'Porta agujas quirúrgicas', 'image_path' => 'materials/porta_agujas.jpg'],
            ['material_id' => 10, 'name' => 'Mangos Bisturí nº4', 'description' => 'Mangos para bisturí número 4', 'image_path' => 'materials/mangos_bisturi_n4.jpg'],
            ['material_id' => 11, 'name' => 'Bisturí Desechable', 'description' => 'Bisturí desechable', 'image_path' => 'materials/bisturi_desechable.jpg'],
            ['material_id' => 12, 'name' => 'Quitagrapas', 'description' => 'Instrumento para retirar grapas', 'image_path' => 'materials/quitagrapas.jpg'],
            ['material_id' => 13, 'name' => 'Bisturí Eléctrico', 'description' => 'Bisturí eléctrico', 'image_path' => 'materials/bisturi_electrico.jpg'],
            ['material_id' => 14, 'name' => 'Tapones Sonda (Caja)', 'description' => 'Tapones para sonda (caja)', 'image_path' => 'materials/tapones_sonda_caja.jpg'],
            ['material_id' => 15, 'name' => 'Tapones Vía (Caja)', 'description' => 'Tapones para vía (caja)', 'image_path' => null],
            ['material_id' => 16, 'name' => 'Llaves 3 Vías c/ y s/ Alargadera', 'description' => 'Llaves de 3 vías con y sin alargadera', 'image_path' => 'materials/llaves_3_vias_c_y_s_alargadera.jpg'],
            ['material_id' => 17, 'name' => 'Cánulas Traqueostomía', 'description' => 'Cánulas para traqueostomía', 'image_path' => 'materials/canulas_traqueostomia.jpg'],
            ['material_id' => 18, 'name' => 'Tracción Adhesiva a Piel', 'description' => 'Sistema de tracción adhesiva para la piel', 'image_path' => 'materials/traccion_adhesiva_a_piel.jpg'],
            ['material_id' => 19, 'name' => 'Bolsas Colostomía Abierta 1 Pieza (Caja)', 'description' => 'Bolsas para colostomía abierta (1 pieza)', 'image_path' => null],
            ['material_id' => 20, 'name' => 'Bolsas Colostomía Cerrada 1 Pieza (Caja)', 'description' => 'Bolsas para colostomía cerrada (1 pieza)', 'image_path' => null],
            ['material_id' => 21, 'name' => 'Bolsas Colostomía Cerrada 2 Piezas (Caja)', 'description' => 'Bolsas para colostomía cerrada (2 piezas)', 'image_path' => null],
            ['material_id' => 22, 'name' => 'Apósitos Hidropolimérico Varias Formas', 'description' => 'Apósitos hidropoliméricos en varias formas', 'image_path' => 'materials/apositos_hidropolimerico_varias_formas.jpg'],
            ['material_id' => 23, 'name' => 'Esparadrapo 2,5 cm Papel', 'description' => 'Esparadrapo de papel (2.5 cm)', 'image_path' => null],
            ['material_id' => 24, 'name' => 'Esparadrapo 2,5 cm Microperforado Transparente', 'description' => 'Esparadrapo microperforado transparente (2.5 cm)', 'image_path' => 'materials/esparadrapo_2_5_cm_microperforado_transparente.jpg'],
            ['material_id' => 25, 'name' => 'Apósitos Transparente Vías (Caja)', 'description' => 'Apósitos transparentes para vías (caja)', 'image_path' => 'materials/apositos_transparente_vias_caja.jpg'],
            ['material_id' => 26, 'name' => 'Mepore Varios Tamaños (Caja)', 'description' => 'Apósitos Mepore de varios tamaños (caja)', 'image_path' => null],
            ['material_id' => 27, 'name' => 'Apósito Aquacel Ag+', 'description' => 'Apósito Aquacel Ag+', 'image_path' => 'materials/aposito_aquacel_ag_plus.jpg'],
            ['material_id' => 28, 'name' => 'Linitul (Caja)', 'description' => 'Linitul (caja)', 'image_path' => 'materials/linitul_caja.jpg'],
            ['material_id' => 29, 'name' => 'Mefix', 'description' => 'Apósitos Mefix', 'image_path' => 'materials/mefix.jpg'],
            ['material_id' => 30, 'name' => 'Baberos Traqueostomía (Caja)', 'description' => 'Baberos para traqueostomía (caja)', 'image_path' => 'materials/baberos_traqueostomia_caja.jpg'],
            ['material_id' => 31, 'name' => 'Depresor Lingual (Caja)', 'description' => 'Depresores linguales (caja)', 'image_path' => 'materials/depresor_lingual_caja.jpg'],
            ['material_id' => 32, 'name' => 'Cepillos Dientes c/ Esponja + Aspirador', 'description' => 'Cepillos de dientes con esponja y aspirador', 'image_path' => 'materials/cepillos_dientes_c_esponja_mas_aspirador.jpg'],
            ['material_id' => 33, 'name' => 'SF Monodosis (Caja)', 'description' => 'Solución fisiológica monodosis (caja)', 'image_path' => 'materials/sf_monodosis_caja.jpg'],
            ['material_id' => 34, 'name' => 'Lubricante', 'description' => 'Lubricante médico', 'image_path' => 'materials/lubricante.jpg'],
            ['material_id' => 35, 'name' => 'Jeringas 5ml', 'description' => 'Jeringas desechables de 5 ml', 'image_path' => 'materials/jeringas_5ml.jpg'],
            ['material_id' => 36, 'name' => 'Jeringas 10ml', 'description' => 'Jeringas desechables de 10 ml', 'image_path' => 'materials/jeringas_10ml.jpg'],
            ['material_id' => 37, 'name' => 'Guantes Nitrilo Talla M', 'description' => 'Guantes de nitrilo sin polvo talla M', 'image_path' => 'materials/guantes_nitrilo_m.jpg'],
            ['material_id' => 38, 'name' => 'Guantes Nitrilo Talla L', 'description' => 'Guantes de nitrilo sin polvo talla L', 'image_path' => 'materials/guantes_nitrilo_l.jpg'],
            ['material_id' => 39, 'name' => 'Mascarilla Quirúrgica', 'description' => 'Mascarilla quirúrgica desechable', 'image_path' => 'materials/mascarilla_quirurgica.jpg'],
            ['material_id' => 40, 'name' => 'Mascarilla FFP2', 'description' => 'Mascarilla de protección FFP2', 'image_path' => 'materials/mascarilla_ffp2.jpg'],
            ['material_id' => 41, 'name' => 'Batas Desechables', 'description' => 'Batas desechables para procedimientos', 'image_path' => 'materials/batas_desechables.jpg'],
            ['material_id' => 42, 'name' => 'Campo Estéril', 'description' => 'Campo quirúrgico estéril', 'image_path' => 'materials/campo_estéril.jpg'],
            ['material_id' => 43, 'name' => 'Gasas Estériles (Caja)', 'description' => 'Gasas estériles envasadas (caja)', 'image_path' => 'materials/gasas_esteriles.jpg'],
            ['material_id' => 44, 'name' => 'Alcohol 70%', 'description' => 'Solución de alcohol al 70%', 'image_path' => 'materials/alcohol_70.jpg'],
            ['material_id' => 45, 'name' => 'Clorhexidina 2%', 'description' => 'Solución antiséptica de clorhexidina al 2%', 'image_path' => 'materials/clorhexidina.jpg'],
            ['material_id' => 46, 'name' => 'Termómetro Infrarrojo', 'description' => 'Termómetro digital sin contacto', 'image_path' => 'materials/termometro_infrarrojo.jpg'],
            ['material_id' => 47, 'name' => 'Tensiómetro Digital', 'description' => 'Tensiómetro automático de brazo', 'image_path' => 'materials/tensiometro_digital.jpg'],
            ['material_id' => 48, 'name' => 'Fonendoscopio', 'description' => 'Estetoscopio médico', 'image_path' => 'materials/fonendoscopio.jpg'],
            ['material_id' => 49, 'name' => 'Vendas Elásticas', 'description' => 'Vendas de compresión elástica', 'image_path' => 'materials/vendas_elasticas.jpg'],
            ['material_id' => 50, 'name' => 'Vendas Cohesivas', 'description' => 'Vendas que se adhieren a sí mismas', 'image_path' => 'materials/vendas_cohesivas.jpg'],
            ['material_id' => 51, 'name' => 'Tiras Reactivas Glucosa', 'description' => 'Tiras reactivas para glucosa en sangre', 'image_path' => 'materials/tiras_glucosa.jpg'],
            ['material_id' => 52, 'name' => 'Lancetas', 'description' => 'Lancetas para punción capilar', 'image_path' => 'materials/lancetas.jpg'],
            ['material_id' => 53, 'name' => 'Sondas Foley', 'description' => 'Sondas vesicales tipo Foley', 'image_path' => 'materials/sondas_foley.jpg'],
            ['material_id' => 54, 'name' => 'Sondas Nasoentéricas', 'description' => 'Sondas para nutrición enteral', 'image_path' => 'materials/sondas_nasoentericas.jpg'],
            ['material_id' => 55, 'name' => 'Apósito de Espuma', 'description' => 'Apósito absorbente de espuma', 'image_path' => 'materials/aposito_espuma.jpg'],
            ['material_id' => 56, 'name' => 'Apósito Film Transparente', 'description' => 'Apósito tipo film, impermeable y transpirable', 'image_path' => 'materials/aposito_film.jpg'],
            ['material_id' => 57, 'name' => 'Suturas Seda', 'description' => 'Hilos de sutura de seda', 'image_path' => 'materials/suturas_seda.jpg'],
            ['material_id' => 58, 'name' => 'Suturas Reabsorbibles', 'description' => 'Hilos de sutura absorbibles', 'image_path' => 'materials/suturas_reabsorbibles.jpg'],
            ['material_id' => 59, 'name' => 'Cintas Microporosas', 'description' => 'Cintas adhesivas hipoalergénicas', 'image_path' => null],
            ['material_id' => 60, 'name' => 'Frascos de Muestra', 'description' => 'Recipientes estériles para muestras', 'image_path' => 'materials/frascos_muestra.jpg'],
            ['material_id' => 61, 'name' => 'Pulsioxímetro', 'description' => 'Medidor de saturación de oxígeno', 'image_path' => 'materials/pulsioximetro.jpg'],
            ['material_id' => 62, 'name' => 'Gorro Desechable', 'description' => 'Gorro quirúrgico desechable', 'image_path' => 'materials/gorro_desechable.jpg'],
            ['material_id' => 63, 'name' => 'Protector Ocular', 'description' => 'Gafas de protección médica', 'image_path' => 'materials/protector_ocular.jpg'],
            ['material_id' => 64, 'name' => 'Toallitas Antisépticas', 'description' => 'Toallitas con antiséptico para piel', 'image_path' => null],
            ['material_id' => 65, 'name' => 'Cubrecalzado Desechable', 'description' => 'Protección de calzado para entornos estériles', 'image_path' => 'materials/cubrecalzado_desechable.jpg'],
            ['material_id' => 66, 'name' => 'Papel Camilla', 'description' => 'Rollo de papel para cubrir camillas', 'image_path' => 'materials/papel_camilla.jpg'],
            ['material_id' => 67, 'name' => 'Cinta Adhesiva Quirúrgica', 'description' => 'Cinta adhesiva para fijación médica', 'image_path' => 'materials/cinta_adhesiva_quirurgica.jpg'],
            ['material_id' => 68, 'name' => 'Apósito Estéril Adhesivo', 'description' => 'Apósito adhesivo individual estéril', 'image_path' => 'materials/aposito_adhesivo_esteril.jpg'],
            ['material_id' => 69, 'name' => 'Esponjas Jabón Antiséptico', 'description' => 'Esponjas impregnadas con jabón antiséptico', 'image_path' => 'materials/esponjas_jabon_antiseptico.jpg'],
            ['material_id' => 70, 'name' => 'Cánula Nasal O2', 'description' => 'Cánula nasal para oxígeno', 'image_path' => 'materials/canula_nasal_o2.jpg'],
            ['material_id' => 71, 'name' => 'Mascarilla Venturi', 'description' => 'Mascarilla de oxígeno tipo Venturi', 'image_path' => 'materials/mascarilla_venturi.jpg'],
            ['material_id' => 72, 'name' => 'Nebulizador', 'description' => 'Sistema para administración de medicación nebulizada', 'image_path' => 'materials/nebulizador.jpg'],
            ['material_id' => 73, 'name' => 'Tubo Endotraqueal', 'description' => 'Tubo para intubación endotraqueal', 'image_path' => 'materials/tubo_endotraqueal.jpg'],
            ['material_id' => 74, 'name' => 'Bolsa Reanimación (Ambú)', 'description' => 'Bolsa autoinflable para reanimación', 'image_path' => 'materials/bolsa_ambu.jpg'],
            ['material_id' => 75, 'name' => 'Cánula Guedel', 'description' => 'Dispositivo para mantener vía aérea abierta', 'image_path' => 'materials/canula_guedel.jpg'],
            ['material_id' => 76, 'name' => 'Cánula Yankauer', 'description' => 'Cánula de aspiración quirúrgica', 'image_path' => 'materials/canula_yankauer.jpg'],
            ['material_id' => 77, 'name' => 'Drenaje Blake', 'description' => 'Drenaje quirúrgico blando', 'image_path' => null],
            ['material_id' => 78, 'name' => 'Frasco de Drenaje', 'description' => 'Recipiente para drenaje quirúrgico', 'image_path' => 'materials/frasco_drenaje.jpg'],
            ['material_id' => 79, 'name' => 'Jeringa de Irrigación', 'description' => 'Jeringa para lavado quirúrgico o de heridas', 'image_path' => null],
            ['material_id' => 80, 'name' => 'Gel Hidroalcohólico', 'description' => 'Solución hidroalcohólica desinfectante', 'image_path' => 'materials/gel_hidroalcoholico.jpg'],
            ['material_id' => 81, 'name' => 'Termómetro Axilar', 'description' => 'Termómetro clínico para axila', 'image_path' => 'materials/termometro_axilar.jpg'],
            ['material_id' => 82, 'name' => 'Bata Estéril Quirúrgica', 'description' => 'Bata estéril para cirugía', 'image_path' => 'materials/bata_esteril_quirurgica.jpg'],
            ['material_id' => 83, 'name' => 'Campos Quirúrgicos Adhesivos', 'description' => 'Campos adhesivos estériles para cirugía', 'image_path' => null],
            ['material_id' => 84, 'name' => 'Kit de Sutura Desechable', 'description' => 'Kit estéril de sutura de un solo uso', 'image_path' => 'materials/kit_sutura_desechable.jpg'],
            ['material_id' => 85, 'name' => 'Parches Oculares', 'description' => 'Parches estériles para ojos', 'image_path' => 'materials/parches_oculares.jpg'],
            ['material_id' => 86, 'name' => 'Apósito Hemostático', 'description' => 'Apósito para detener hemorragias', 'image_path' => 'materials/aposito_hemostatico.jpg'],
            ['material_id' => 87, 'name' => 'Colector de Orina', 'description' => 'Bolsa colectora de orina con tubo', 'image_path' => 'materials/colector_orina.jpg'],
            ['material_id' => 88, 'name' => 'Cepillos Quirúrgicos', 'description' => 'Cepillos estériles para lavado quirúrgico', 'image_path' => 'materials/cepillos_quirurgicos.jpg'],
            ['material_id' => 89, 'name' => 'Contenedor de Residuos', 'description' => 'Contenedor rígido para residuos sanitarios', 'image_path' => 'materials/contenedor_residuos.jpg'],
            ['material_id' => 90, 'name' => 'Papel Indicador Esterilización', 'description' => 'Indicador químico para ciclos de esterilización', 'image_path' => null],
            ['material_id' => 91, 'name' => 'Tiras Reactivas Orina', 'description' => 'Tiras para análisis de orina', 'image_path' => 'materials/tiras_orina.jpg'],
            ['material_id' => 92, 'name' => 'Spray Antiséptico', 'description' => 'Spray para desinfección cutánea', 'image_path' => 'materials/spray_antiseptico.jpg'],
            ['material_id' => 93, 'name' => 'Esponjas Hemostáticas', 'description' => 'Material absorbente para control de sangrado', 'image_path' => 'materials/esponjas_hemostaticas.jpg'],
            ['material_id' => 94, 'name' => 'Luz Frontal LED', 'description' => 'Luz de cabeza para iluminación en procedimientos', 'image_path' => 'materials/luz_frontal_led.jpg'],
        ]);



        // Seed Storages
        DB::table('storages')->insert([
            ['material_id' => 1,  'storage' => 'odontology', 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 12, 'min_units' => 4],
            ['material_id' => 1,  'storage' => 'odontology', 'storage_type' => 'use',     'cabinet' => '1',             'shelf' => 1, 'drawer' => 1,    'units' => 7,  'min_units' => 8],
            ['material_id' => 1,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 12, 'min_units' => 4],
            ['material_id' => 1,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '1',             'shelf' => 1, 'drawer' => 1,    'units' => 7,  'min_units' => 8],
            ['material_id' => 2,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 4,  'min_units' => 6],
            ['material_id' => 2,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => 1,               'shelf' => 1, 'drawer' => 2,    'units' => 11, 'min_units' => 6],
            ['material_id' => 3,  'storage' => 'odontology', 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 10, 'min_units' => 10],
            ['material_id' => 3,  'storage' => 'odontology', 'storage_type' => 'use',     'cabinet' => 1,               'shelf' => 1, 'drawer' => 1,    'units' => 15, 'min_units' => 13],
            ['material_id' => 4,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 24, 'min_units' => 20],
            ['material_id' => 4,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 2, 'drawer' => 1,    'units' => 12, 'min_units' => 10],
            ['material_id' => 5,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 44, 'min_units' => 19],
            ['material_id' => 5,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 2, 'drawer' => 2,    'units' => 14, 'min_units' => 16],
            ['material_id' => 6,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 16, 'min_units' => 12],
            ['material_id' => 6,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 2, 'drawer' => 3,    'units' => 32, 'min_units' => 32],
            ['material_id' => 7,  'storage' => 'odontology', 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 52, 'min_units' => 42],
            ['material_id' => 7,  'storage' => 'odontology', 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 3, 'drawer' => 1,    'units' => 8,  'min_units' => 14],
            ['material_id' => 7,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 1, 'drawer' => null, 'units' => 52, 'min_units' => 42],
            ['material_id' => 7,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 3, 'drawer' => 1,    'units' => 8,  'min_units' => 14],
            ['material_id' => 8,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 2, 'drawer' => null, 'units' => 26, 'min_units' => 23],
            ['material_id' => 8,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 3, 'drawer' => 2,    'units' => 27, 'min_units' => 26],
            ['material_id' => 9,  'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 2, 'drawer' => null, 'units' => 12, 'min_units' => 10],
            ['material_id' => 9,  'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 3, 'drawer' => 3,    'units' => 17, 'min_units' => 14],
            ['material_id' => 10, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 2, 'drawer' => null, 'units' => 15, 'min_units' => 11],
            ['material_id' => 10, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 4, 'drawer' => 1,    'units' => 11, 'min_units' => 12],
            ['material_id' => 11, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 2, 'drawer' => null, 'units' => 18, 'min_units' => 13],
            ['material_id' => 11, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 4, 'drawer' => 2,    'units' => 13, 'min_units' => 15],
            ['material_id' => 12, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 3, 'drawer' => null, 'units' => 19, 'min_units' => 17],
            ['material_id' => 12, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 4, 'drawer' => 3,    'units' => 11, 'min_units' => 13],
            ['material_id' => 13, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 3, 'drawer' => null, 'units' => 22, 'min_units' => 13],
            ['material_id' => 13, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 5, 'drawer' => 1,    'units' => 20, 'min_units' => 17],
            ['material_id' => 14, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 3, 'drawer' => null, 'units' => 22, 'min_units' => 21],
            ['material_id' => 14, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 5, 'drawer' => 2,    'units' => 15, 'min_units' => 13],
            ['material_id' => 15, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario gris',  'shelf' => 4, 'drawer' => null, 'units' => 23, 'min_units' => 11],
            ['material_id' => 15, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 5, 'drawer' => 3,    'units' => 24, 'min_units' => 13],
            ['material_id' => 16, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario rojo',  'shelf' => 4, 'drawer' => null, 'units' => 23, 'min_units' => 14],
            ['material_id' => 16, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 6, 'drawer' => 1,    'units' => 19, 'min_units' => 13],
            ['material_id' => 17, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario rojo',  'shelf' => 4, 'drawer' => null, 'units' => 20, 'min_units' => 14],
            ['material_id' => 17, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 6, 'drawer' => 2,    'units' => 21, 'min_units' => 17],
            ['material_id' => 18, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario rojo',  'shelf' => 5, 'drawer' => null, 'units' => 10, 'min_units' => 13],
            ['material_id' => 18, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 6, 'drawer' => 3,    'units' => 12, 'min_units' => 11],
            ['material_id' => 19, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario rojo',  'shelf' => 5, 'drawer' => null, 'units' => 35, 'min_units' => 11],
            ['material_id' => 19, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 7, 'drawer' => 1,    'units' => 32, 'min_units' => 32],
            ['material_id' => 20, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario rojo',  'shelf' => 5, 'drawer' => null, 'units' => 20, 'min_units' => 17],
            ['material_id' => 20, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 7, 'drawer' => 2,    'units' => 23, 'min_units' => 17],
            ['material_id' => 21, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario rojo',  'shelf' => 6, 'drawer' => null, 'units' => 17, 'min_units' => 12],
            ['material_id' => 21, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 7, 'drawer' => 3,    'units' => 33, 'min_units' => 51],
            ['material_id' => 22, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario rojo',  'shelf' => 6, 'drawer' => null, 'units' => 8,  'min_units' => 2 ],
            ['material_id' => 22, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 8, 'drawer' => 1,    'units' => 13, 'min_units' => 12],
            ['material_id' => 23, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario verde', 'shelf' => 6, 'drawer' => null, 'units' => 29, 'min_units' => 45],
            ['material_id' => 23, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 8, 'drawer' => 2,    'units' => 11, 'min_units' => 9 ],
            ['material_id' => 24, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario verde', 'shelf' => 7, 'drawer' => null, 'units' => 15, 'min_units' => 10],
            ['material_id' => 24, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 8, 'drawer' => 3,    'units' => 12, 'min_units' => 11],
            ['material_id' => 25, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario verde', 'shelf' => 7, 'drawer' => null, 'units' => 23, 'min_units' => 24],
            ['material_id' => 25, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 9, 'drawer' => 1,    'units' => 14, 'min_units' => 12],
            ['material_id' => 26, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario verde', 'shelf' => 7, 'drawer' => null, 'units' => 3,  'min_units' => 2],
            ['material_id' => 26, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 9, 'drawer' => 2,    'units' => 9,  'min_units' => 8 ],
            ['material_id' => 27, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario verde', 'shelf' => 8, 'drawer' => null, 'units' => 32, 'min_units' => 26],
            ['material_id' => 27, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 9, 'drawer' => 3,    'units' => 20, 'min_units' => 24],
            ['material_id' => 28, 'storage' => 'CAE'       , 'storage_type' => 'reserve', 'cabinet' => 'armario verde', 'shelf' => 8, 'drawer' => null, 'units' => 20, 'min_units' => 15],
            ['material_id' => 28, 'storage' => 'CAE'       , 'storage_type' => 'use',     'cabinet' => '2',             'shelf' => 10, 'drawer' => 1,   'units' => 20, 'min_units' => 15],

        ]);

        // Seed Modifications
        DB::table('modifications')->insert([
            ['user_id' => 1, 'material_id' => 1, 'storage' => 'CAE', 'storage_type' => 'reserve',  'units' => 10, 'action_datetime' => now()],
            ['user_id' => 2, 'material_id' => 2, 'storage' => 'CAE', 'storage_type' => 'use', 'units' => -5, 'action_datetime' => now()->subDays(5)],
            ['user_id' => 3, 'material_id' => 1, 'storage' => 'CAE', 'storage_type' => 'reserve', 'units' => -3, 'action_datetime' => now()->subDays(10)],
            ['user_id' => 1, 'material_id' => 1, 'storage' => 'CAE', 'storage_type' => 'reserve', 'units' => 15, 'action_datetime' => now()->subDays(3)],
            ['user_id' => 2, 'material_id' => 2, 'storage' => 'CAE', 'storage_type' => 'use',  'units' => -5, 'action_datetime' => now()->subDays(7)],
            ['user_id' => 3, 'material_id' => 1, 'storage' => 'CAE', 'storage_type' => 'reserve', 'units' => -8, 'action_datetime' => now()->subDays(2)],
            ['user_id' => 1, 'material_id' => 1, 'storage' => 'odontology', 'storage_type' => 'reserve',  'units' => 12, 'action_datetime' => now()->subDays(4)],
            ['user_id' => 3, 'material_id' => 3, 'storage' => 'odontology', 'storage_type' => 'use', 'units' => -4, 'action_datetime' => now()->subDays(6)],
            ['user_id' => 1, 'material_id' => 7, 'storage' => 'odontology', 'storage_type' => 'use', 'units' => 9, 'action_datetime' => now()->subDays(1)],
        ]);

        // Seed Activities
        DB::table('activities')->insert([
            ['user_id' => 3, 'title' => 'Taller de Cuidado de Heridas',          'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(1)],
            ['user_id' => 3, 'title' => 'Técnicas de Esterilización',            'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(2)],
            ['user_id' => 3, 'title' => 'Práctica de Suturas',                   'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(3)],
            ['user_id' => 3, 'title' => 'Simulacro de Respuesta a Emergencias', 'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(4)],
            ['user_id' => 3, 'title' => 'Introducción a Instrumentos Quirúrgicos','teacher_id' => 7, 'created_at' => Carbon::now()->subDays(5)],
            ['user_id' => 3, 'title' => 'Sesión de Laboratorio de Anatomía',     'teacher_id' => 7, 'created_at' => Carbon::now()->subDays(6)],
            ['user_id' => 3, 'title' => 'Conceptos Básicos de Manejo de Pacientes','teacher_id' => 7, 'created_at' => Carbon::now()->subDays(7)],
            ['user_id' => 3, 'title' => 'Control de Infecciones',                'teacher_id' => 6, 'created_at' => Carbon::now()->subDays(8)],
            ['user_id' => 3, 'title' => 'Resumen de Farmacología',               'teacher_id' => 6, 'created_at' => Carbon::now()->subDays(9)],
            ['user_id' => 3, 'title' => 'Primeros Auxilios Avanzados',           'teacher_id' => 6, 'created_at' => Carbon::now()->subDays(10)],

            ['user_id' => 4, 'title' => 'Taller de Cuidado de Heridas',          'teacher_id' => 6, 'created_at' => Carbon::now()->subDays(1)],
            ['user_id' => 4, 'title' => 'Técnicas de Esterilización',            'teacher_id' => 6, 'created_at' => Carbon::now()->subDays(2)],
            ['user_id' => 4, 'title' => 'Práctica de Suturas',                   'teacher_id' => 7, 'created_at' => Carbon::now()->subDays(3)],
            ['user_id' => 4, 'title' => 'Simulacro de Respuesta a Emergencias', 'teacher_id' => 7, 'created_at' => Carbon::now()->subDays(4)],
            ['user_id' => 4, 'title' => 'Introducción a Instrumentos Quirúrgicos','teacher_id' => 7, 'created_at' => Carbon::now()->subDays(5)],
            ['user_id' => 4, 'title' => 'Sesión de Laboratorio de Anatomía',     'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(6)],
            ['user_id' => 4, 'title' => 'Conceptos Básicos de Manejo de Pacientes','teacher_id' => 5, 'created_at' => Carbon::now()->subDays(7)],
            ['user_id' => 4, 'title' => 'Control de Infecciones',                'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(8)],
            ['user_id' => 4, 'title' => 'Resumen de Farmacología',               'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(9)],
            ['user_id' => 4, 'title' => 'Primeros Auxilios Avanzados',           'teacher_id' => 5, 'created_at' => Carbon::now()->subDays(10)],
        ]);


        // Seed Material-Activity pivot
        DB::table('material_activity')->insert([
            ['activity_id' => 2, 'material_id' => 2,  'units' => 5],
            ['activity_id' => 2, 'material_id' => 5,  'units' => 5],
            ['activity_id' => 2, 'material_id' => 6,  'units' => 15],
            ['activity_id' => 3, 'material_id' => 3,  'units' => 7],
            ['activity_id' => 3, 'material_id' => 2,  'units' => 1],
            ['activity_id' => 4, 'material_id' => 1,  'units' => 10],
            ['activity_id' => 5, 'material_id' => 4,  'units' => 8],
            ['activity_id' => 6, 'material_id' => 4,  'units' => 1],
            ['activity_id' => 6, 'material_id' => 5,  'units' => 6],
            ['activity_id' => 7, 'material_id' => 6,  'units' => 4],
            ['activity_id' => 8, 'material_id' => 7,  'units' => 9],
            ['activity_id' => 9, 'material_id' => 8,  'units' => 3],
            ['activity_id' => 9, 'material_id' => 10, 'units' => 1],
            ['activity_id' => 9, 'material_id' => 1,  'units' => 2],
            ['activity_id' => 9, 'material_id' => 3,  'units' => 1],
            ['activity_id' => 10,'material_id' => 9,  'units' => 2],
            ['activity_id' => 11,'material_id' => 10, 'units' => 5],
            ['activity_id' => 12,'material_id' => 11, 'units' => 7],
            ['activity_id' => 13,'material_id' => 12, 'units' => 6],
            ['activity_id' => 14,'material_id' => 13, 'units' => 8],
            ['activity_id' => 15,'material_id' => 14, 'units' => 4],
            ['activity_id' => 16,'material_id' => 15, 'units' => 3],
            ['activity_id' => 17,'material_id' => 16, 'units' => 7],
            ['activity_id' => 18,'material_id' => 17, 'units' => 5],
            ['activity_id' => 19,'material_id' => 18, 'units' => 6],
        ]);
    }
}
